services:
  postgres:
    image: postgres:14
    hostname: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  task-service:
    # build the image first using `mvn clean spring-boot:build-image -pl task-service`
    image: docker.io/library/task-service:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - "8082:8080"

  # build the image first using `mvn clean spring-boot:build-image -pl user-service`
  user-service:
    image: docker.io/library/user-service:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - "8081:8080"

volumes:
  postgres-data:
