logging:
  level:
    web: INFO
    org.springframework.web: INFO
    se.myrthe: TRACE
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: myuser
    password: mypassword
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop
